#!/usr/bin/env python3
"""Generate the per-panel ESPHome files, the add-on rooms: block, and a label
sheet for the back of each unit.

    python3 tools/make_rooms.py rooms.csv

rooms.csv columns:
    panel_id,room_id,name,mailbox,static_ip,capacity
e.g.
    panel-01,boardroom,Boardroom,boardroom@lwyd.in,10.0.0.101,12

panel_id is the physical unit; room_id is the door. Keeping them separate is
what lets you reassign a panel in config instead of reflashing it.
"""
import csv
import json
import pathlib
import sys

NET = {"renderer": "http://10.0.0.5:8099", "gateway": "10.0.0.1",
       "subnet": "255.255.255.0", "dns1": "10.0.0.1"}

TEMPLATE = """# generated by tools/make_rooms.py -- edit rooms.csv and re-run
substitutions:
  panel_id: "{panel_id}"
  friendly_name: "{name}"
  static_ip: "{static_ip}"
  renderer: "{renderer}"
  gateway: "{gateway}"
  subnet: "{subnet}"
  dns1: "{dns1}"

packages:
  base: !include huddle-base.yaml
"""


def main(path: str) -> None:
    out_dir = pathlib.Path("esphome")
    out_dir.mkdir(exist_ok=True)
    rooms, labels = [], []

    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            row = {k.strip(): (v or "").strip() for k, v in row.items()}
            row.setdefault("panel_id", row["room_id"])
            (out_dir / f"{row['panel_id']}.yaml").write_text(TEMPLATE.format(**row, **NET))

            entry = {
                "room_id": row["room_id"],
                "name": row["name"],
                "calendar_entity": f"calendar.room_{row['room_id'].replace('-', '_')}",
                "mailbox": row["mailbox"],
                "panel_id": row["panel_id"],
            }
            if row.get("capacity"):
                entry["capacity"] = int(row["capacity"])
            rooms.append(entry)
            labels.append((row["panel_id"], row["name"], row["static_ip"]))
            print(f"wrote esphome/{row['panel_id']}.yaml")

    print("\n--- paste into the add-on configuration ---")
    print(json.dumps({"rooms": rooms}, indent=2))

    sheet = pathlib.Path("PANEL-LABELS.txt")
    col = max(len(n) for _, n, _ in labels) + 2
    inner = 2 + 12 + col                      # "  " + panel_id field + name field
    rule = "+" + "-" * inner + "+"
    lines = ["PANEL LABELS - stick one on the back of each unit",
             "Support: after charging, this panel goes back on this door.", ""]
    for pid, name, ip in labels:
        lines += [rule,
                  f"|  {pid:<12}{name:<{col}}|",
                  f"|  {ip:<12}{'':<{col}}|",
                  rule, ""]
    sheet.write_text("\n".join(lines))
    print(f"\nwrote {sheet} ({len(labels)} labels)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "rooms.csv")
